export const ERROR_CODES = [
  'INVALID_CREDENTIALS',
  'INVALID_REFRESH_TOKEN',
  'ACCESS_DENIED',
  'FORBIDDEN_ROLE',
  'FORBIDDEN_USER_READ',
  'FORBIDDEN_USER_UPDATE',
  'FORBIDDEN_USER_DELETE',
  'FORBIDDEN_TASK_UPDATE',
  'FORBIDDEN_TASK_DELETE',
  'USER_NOT_FOUND',
  'TASK_NOT_FOUND',
  'USERNAME_TAKEN',
  'USER_HAS_TASKS',
  'VALIDATION_ERROR',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'NOT_FOUND',
  'INTERNAL_SERVER_ERROR',
  'TASK_CREATE_ERROR',
] as const;

export type ErrorCode = typeof ERROR_CODES[number];